// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9-BRmdBMF9g3wF-gbnbePrwH3a8_I3VI',
    appId: '1:262059908754:web:fe9ab213df18bab878104b',
    messagingSenderId: '262059908754',
    projectId: 'chat-app-704de',
    authDomain: 'chat-app-704de.firebaseapp.com',
    databaseURL: 'https://chat-app-704de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-704de.appspot.com',
    measurementId: 'G-F8KTH5HK31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbB-u4gZT4odPDRjvPAUsgLV52dtKleEM',
    appId: '1:262059908754:android:7332be3574044ff978104b',
    messagingSenderId: '262059908754',
    projectId: 'chat-app-704de',
    databaseURL: 'https://chat-app-704de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-704de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0X10EKZqt_XgfcqMX1YyV2b_hXKJPvXs',
    appId: '1:262059908754:ios:f1e6263b7fcc14d978104b',
    messagingSenderId: '262059908754',
    projectId: 'chat-app-704de',
    databaseURL: 'https://chat-app-704de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-704de.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0X10EKZqt_XgfcqMX1YyV2b_hXKJPvXs',
    appId: '1:262059908754:ios:b3392c8dab0a758b78104b',
    messagingSenderId: '262059908754',
    projectId: 'chat-app-704de',
    databaseURL: 'https://chat-app-704de-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'chat-app-704de.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
